Suggestion for docker-compose DX improvements
starlite-api/backend-starlite-postgres pull request #3
Opened 2022-01-24 19:02 UTC by sondrelg

Hi @yudjinn,

This PR is a bit messy, but I wanted to suggest a few changes, without needing to fully realize them.

What do you think about:

- Adding an entrypoint for ready checking postgres and redis
- Splitting the dockerfile into stages
- Making alembic use asyncpg and dropping psycopg2
- Adding uvloop
- Adding a logging configuration setup
- Adding a `gunicorn.conf.py` which dynamically checks the CPU count of the client and sets an appropriate gunicorn worker count
- Adding aioredis

The rest of the changes are largely noise. I started adding `databases` but I think that might be a mistake for this project.

2022-01-24 19:58 UTC, Goldziher commented on app/core/database.py
> +    if not state.database:
instead of importing state from app.core, i would inject state as an argument. Starlite is not FastAPI/Starlette, and it supports this:

https://starlite-api.github.io/starlite/usage/0-the-starlite-app/#using-application-state

2022-01-24 19:58 UTC, Goldziher commented on app/core/database.py
> +    if state.database.is_connected:
same

2022-01-24 19:59 UTC, Goldziher commented on app/core/logging.py
> +def configure_logging() -> None:
Starlite has a simple asbtraction for this:

https://starlite-api.github.io/starlite/usage/0-the-starlite-app/#logging

2022-01-24 19:59 UTC, Goldziher commented on app/core/redis.py
> +    if state.redis is not None:
same regarding state

2022-01-24 20:00 UTC, Goldziher commented on app/core/redis.py
> +    if state.redis:
same

2022-01-24 20:00 UTC, Goldziher commented on app/core/uvloop.py
> +async def configure_uvloop() -> None:
is this required or is that already bundled with uvicorn + standard?

2022-01-24 20:01 UTC, Goldziher commented on app/main.py
> +    await asyncio.gather(
this is an optimization that will have millisecond effects on startup time. Why not simply pass the functions to the on_startup and on_shutdown handlers?

2022-01-24 20:04 UTC, Goldziher commented on scripts/entrypoint.sh
> +#!/bin/bash
why evaluate strings rather than have a python file?

2022-01-24 21:07 UTC, sondrelg commented on app/core/uvloop.py
> +async def configure_uvloop() -> None:
required I believe: https://github.com/MagicStack/uvloop

2022-01-24 21:08 UTC, sondrelg commented on app/main.py
> +    await asyncio.gather(
Because you, in my case, might add something like a background task setup that will share the startup/shutdown handlers.

2022-01-24 21:59 UTC, yudjinn requested changes

2022-01-24 21:59 UTC, yudjinn commented on .vscode/settings.json
> -{
why was this deleted?

2022-01-24 21:59 UTC, yudjinn commented on app/core/logging.py
> +def configure_logging() -> None:
doubling on this note, it should be handled using the starlite app logging

2022-01-24 21:59 UTC, yudjinn commented on app/core/state.py
> +from typing import TYPE_CHECKING
we should be able to add this to the global app state, see how the db connection is initiated.

2022-01-24 21:59 UTC, yudjinn commented on app/core/state.py
> +from typing import TYPE_CHECKING
correction, how app.db handled the connection

2022-01-24 21:59 UTC, yudjinn commented on app/repositories/base.py
>      @staticmethod
I initially went the repo route because I planned on this being serviceable for larger apps, but I'm not sure if thats the best option for this example project; what do you think?

2022-01-24 21:59 UTC, yudjinn commented on gunicorn.conf.py
> +# Only runnable on linux
how will this affect local development? or is the gunicorn.conf only intended for server-side deployment?

2022-01-24 21:59 UTC, yudjinn commented on pyproject.toml
> +aioredis = "^2.0.1"
we should set all of these to * for the project

2022-01-24 22:32 UTC, sondrelg commented on .vscode/settings.json
> -{
I don't use vscode, so just deleted it temporarily - shouldn't have commit the changes.

2022-01-24 22:34 UTC, sondrelg commented on app/repositories/base.py
>      @staticmethod
I don't really have a lot of experience using sqlalchemy directly, but doesn't sqlalchemy already ship with a similar ORM?

2022-01-24 22:35 UTC, sondrelg commented on gunicorn.conf.py
> +# Only runnable on linux
Only for deployment - I'd generally favor using uvicorn for local development.

2022-01-24 22:36 UTC, sondrelg commented on scripts/entrypoint.sh
> +#!/bin/bash
no reason other than that all the readiness logic is contained in a single file

2022-01-24 22:37 UTC, sondrelg commented
I know there's plenty of things to pick apart in the PR generally, but what do you think about the individual points I listed above? My thinking was that I could follow this up with individual PRs rather than do this all at once.

2022-01-25 04:08 UTC, yudjinn commented
Inline:
> 
> * Adding an entrypoint for ready checking postgres and redis
**by entrypoint do you mean an endpoint? like a health check?**
> * Splitting the dockerfile into stages
** sounds great!**
> * Making alembic use asyncpg and dropping psycopg2
** also a great change!**
> * Adding uvloop
** not familiar, I'd love to hear what this does/means, you can shoot me a DM on discord if that works best or we can setup a call**
> * Adding a logging configuration setup
** starlite already has support for defining logging config, so we can just follow the docs and have one**
> * Adding a `gunicorn.conf.py` which dynamically checks the CPU count of the client and sets an appropriate gunicorn worker count
** wondering how this interacts with a local dev environment. I dont want 25 workers on my home computer when I only need 1 for dev **
> * Adding aioredis
** unsure the specific use-case, can you elaborate?**

2022-01-25 08:09 UTC, sondrelg commented
> by entrypoint do you mean an endpoint? like a health check?

See the entrypoint.sh here. Essentially, the 

```
depends_on:
    - redis
    - postgres
```

feature of docker compose is not sufficient. Docker compose will spin up the web server as soon as it gets a ready signal from postgres, but in some cases postgres will restart as a part of initialization. In these cases, the web server will crash.

By adding the code in `entrypoint.sh` we get proper readiness checking + a place to run configuration check and migrations

> wondering how this interacts with a local dev environment. I dont want 25 workers on my home computer when I only need 1 for dev

Yeah this is only for deployment, but still useful to contain in a demo repo in my opinion.

> unsure the specific use-case, can you elaborate?

A cache is a fundamental part of most web projects these days, so adding redis to the docker-compose file + adding a suitable async compatible library seems like a good thing. Aioredis is what I'm most familiar with 🙂 

---------------------

Cool, I'll see if I can create some smaller PRs for some of these points, and I guess we can take it from there 👍 Thanks!

2022-01-25 08:09 UTC, closed without merging